#include <iostream>
#define a
#define able
#define abort
#define aborting
#define about
#define absolutely
#define absurd
#define according
#define account
#define across
#define action
#define actor
#define actual
#define actually
#define adam
#define addicted
#define adjusted
#define adrenaline
#define ads
#define advancement
#define advantage
#define advisory
#define affect
#define affects
#define affirmative
#define afraid
#define after
#define afternoon
#define aftertaste
#define again
#define against
#define agreed
#define ahead
#define aim
#define aiming
#define air
#define airport
#define alaska
#define alert
#define alive
#define all
#define allergic
#define allow
#define almost
#define alone
#define already
#define also
#define always
#define am
#define amazing
#define amen
#define amusement
#define an
#define anchor
#define and_
#define angel
#define anger
#define angry
#define animal
#define animals
#define another
#define ant
#define antennae
#define antennas
#define antonio
#define anxiously
#define any
#define anybody
#define anyone
#define anyones
#define anything
#define anyway
#define anywhere
#define approach
#define appropriate
#define approved
#define are
#define area
#define arent
#define around
#define arousing int main() {std::cout << "Bee Movie" << std::endl;}
#define artie
#define artificial
#define as
#define ask
#define asked
#define aspect
#define associate
#define assume
#define assuming
#define at
#define athletic
#define attack
#define attempting
#define attendants
#define attention
#define attorney
#define attracted
#define authorities
#define autograph
#define automatic
#define automatically
#define autopilot
#define available
#define aviation
#define aware
#define away
#define awful
#define awfully
#define awkward
#define b
#define babbling
#define babyll
#define back
#define backhands
#define bad
#define badfella
#define balance
#define bald
#define balloon
#define balls
#define balm
#define band
#define barely
#define barricade
#define barrier
#define barry
#define base
#define bats
#define battery
#define be
#define beams
#define bear
#define beards
#define bears
#define beast
#define beautiful
#define because
#define bed
#define bedbug
#define bee
#define beekeeper
#define beekeepers
#define been
#define beep
#define beer
#define bees
#define before
#define begin
#define begins
#define behind
#define being
#define bejesus
#define belated
#define believe
#define believed
#define belong
#define benefit
#define benson
#define bent
#define best
#define bet
#define better
#define between
#define big
#define billion
#define birds
#define birth
#define bit
#define biting
#define black
#define blacktop
#define blade
#define blend
#define blew
#define blinked
#define blood
#define bloome
#define blossom
#define blow
#define blows
#define blue
#define bluffing
#define boat
#define bob
#define body
#define bogus
#define book
#define boots
#define bored
#define born
#define borrow
#define both
#define bothering
#define bottom
#define bounty
#define bouquets
#define bowl
#define box
#define boy
#define boys
#define brain
#define brave
#define brazenly
#define bread
#define break
#define breakfast
#define breaking
#define breath
#define breathe
#define breaths
#define bred
#define briefcase
#define bright
#define bring
#define bringing
#define britches
#define brochure
#define brooch
#define brooms
#define bs
#define bubble
#define bud
#define buddy
#define bug
#define bugging
#define bugs
#define build
#define building
#define bumble
#define bumbleton
#define business
#define businesses
#define busted
#define busy
#define but
#define buttocks
#define buzz
#define buzzwell
#define buzzy
#define by
#define bye
#define cab
#define cafeteria
#define cake
#define california
#define call
#define called
#define calories
#define campaign
#define camps
#define can
#define candy
#define cannonball
#define cannot
#define cant
#define capable
#define captain
#define capture
#define car
#define card
#define care
#define career
#define careful
#define carefully
#define carl
#define carob
#define case
#define casually
#define catch
#define catches
#define cause
#define celebrate
#define celebrating
#define celery
#define center
#define century
#define ceremonies
#define chance
#define change
#define changes
#define chapstick
#define charges
#define check
#define cheering
#define cheese
#define chemical
#define children
#define chill
#define chips
#define choice
#define choices
#define choose
#define chopsticks
#define chung
#define church
#define churning
#define chute
#define cicada
#define cinnabon
#define cinnamon
#define circular
#define circumstances
#define city
#define class
#define classy
#define clean
#define clear
#define clients
#define cloning
#define close
#define closed
#define clothes
#define cloudy
#define coaster
#define cockpit
#define coffee
#define collectively
#define collector
#define college
#define color
#define colored
#define combined
#define come
#define comes
#define coming
#define common
#define community
#define compadres
#define companies
#define company
#define compelling
#define compete
#define competition
#define complete
#define completely
#define comrades
#define concentrate
#define concludes
#define congratulations
#define consider
#define considered
#define conspiracy
#define constantly
#define contoured
#define contraption
#define control
#define controls
#define cool
#define coolest
#define cooling
#define coordinator
#define copilot
#define copy
#define corrected
#define correctly
#define cotton
#define couch
#define could
#define couldnt
#define counting
#define county
#define couple
#define course
#define coursing
#define court
#define courts
#define cousin
#define cousins
#define covered
#define crashing
#define crazy
#define cream
#define creatures
#define creep
#define crew
#define cricket
#define crime
#define crossed
#define crowds
#define crud
#define crumb
#define cry
#define culture
#define cup
#define cups
#define cut
#define cute
#define da
#define dad
#define dada
#define daffodil
#define daisies
#define damage
#define dangerous
#define dash
#define date
#define dated
#define dating
#define dave
#define dawg
#define day
#define days
#define dead
#define deadified
#define deady
#define deal
#define dean
#define death
#define decide
#define decision
#define decisions
#define decks
#define dee
#define degrees
#define delay
#define deli
#define demand
#define denouncing
#define deny
#define depends
#define desk
#define destruction
#define detail
#define developing
#define devilishly
#define diabolical
#define did
#define didnt
#define die
#define died
#define difference
#define different
#define difficult
#define dirty
#define disaster
#define disconcerting
#define discussing
#define disease
#define dismissal
#define distant
#define distinctive
#define distinguished
#define disturbing
#define divine
#define division
#define do
#define doctor
#define doctored
#define documentary
#define does
#define doesnt
#define doggone
#define dogs
#define doing
#define dollar
#define done
#define dont
#define dots
#define down
#define downstairs
#define downtown
#define drag
#define dragonfly
#define drain
#define drapes
#define dream
#define dreaming
#define dress
#define dressed
#define drive
#define driving
#define drop
#define dude
#define dumb
#define during
#define dustbuster
#define dying
#define dynamite
#define ear
#define earned
#define earth
#define easy
#define eat
#define eating
#define ecstasy
#define ehghty
#define eight
#define eighteen
#define eighth
#define eighties
#define eighty
#define elastic
#define elected
#define em
#define emmy
#define emotion
#define emotional
#define employ
#define employment
#define end
#define engines
#define enjoy
#define enough
#define entire
#define equals
#define er
#define ers
#define even
#define evening
#define events
#define ever
#define every
#define everybody
#define everyone
#define everything
#define everywhere
#define evidence
#define exactly
#define example
#define except
#define excited
#define excuse
#define exhausting
#define existence
#define experience
#define explain
#define exploded
#define exploiting
#define eye
#define eyes
#define face
#define faces
#define fact
#define faculty
#define fairy
#define fake
#define falls
#define familiar
#define fantastic
#define far
#define farm
#define farms
#define fashion
#define fast
#define faster
#define fat
#define fatal
#define father
#define fathers
#define fault
#define favor
#define favorite
#define feel
#define feeling
#define felled
#define fellow
#define felt
#define few
#define fiasco
#define field
#define fifteen
#define filthy
#define final
#define finally
#define find
#define finds
#define fine
#define finish
#define first
#define fit
#define five
#define flabbergasted
#define flames
#define flayman
#define flew
#define flies
#define flight
#define float
#define floats
#define floral
#define florist
#define florists
#define flower
#define flowered
#define flowers
#define flush
#define fly
#define flying
#define fold
#define folds
#define follow
#define food
#define fool
#define for
#define force
#define forcibly
#define forever
#define forget
#define former
#define formula
#define forward
#define four
#define fozzie
#define frankie
#define freak
#define freaks
#define free
#define freeze
#define fresh
#define fried
#define friend
#define friends
#define from
#define front
#define frosting
#define fruits
#define ftd
#define full
#define fun
#define functioning
#define funeral
#define funny
#define fuzz
#define fuzzy
#define gallons
#define game
#define games
#define gandhi
#define ganic
#define garnishments
#define gate
#define gel
#define genius
#define gentlemen
#define get
#define gets
#define getting
#define giant
#define gift
#define girl
#define girlfriend
#define girls
#define give
#define giving
#define glad
#define glasses
#define global
#define glorification
#define glow
#define gnarly
#define go
#define god
#define goes
#define going
#define gold
#define golden
#define gone
#define gonna
#define good
#define goodbye
#define goodfella
#define goodness
#define gordon
#define got
#define gotta
#define gotten
#define grab
#define grabby
#define grade
#define graduate
#define graduating
#define graduation
#define grandmother
#define granny
#define grasshopper
#define grateful
#define great
#define greater
#define greatest
#define gross
#define ground
#define group
#define growing
#define guatemalan
#define guess
#define guest
#define gun
#define gusty
#define guy
#define guys
#define had
#define hair
#define hairy
#define hal
#define half
#define hallelujah
#define hands
#define handsome
#define hang
#define hangs
#define haphazardly
#define happened
#define happening
#define happens
#define happiest
#define happy
#define hard
#define harder
#define harmless
#define harrys
#define has
#define hat
#define hate
#define have
#define havent
#define having
#define he
#define head
#define headed
#define heads
#define health
#define hear
#define heard
#define heart
#define heat
#define heating
#define heaving
#define hector
#define hed
#define hell
#define hello
#define helmet
#define help
#define helping
#define helpless
#define her
#define hercules
#define here
#define heres
#define hes
#define hexagon
#define hey
#define hi
#define high
#define him
#define himits
#define his
#define history
#define hit
#define hitchhiked
#define hitting
#define hive
#define hives
#define hivo
#define hockey
#define hold
#define hollywood
#define holographic
#define home
#define homes
#define honesco
#define honex
#define honey
#define honeybee
#define honeybees
#define honeyburton
#define honeys
#define honor
#define honorable
#define honron
#define hope
#define hoping
#define horrible
#define hot
#define hothead
#define hotter
#define hottest
#define hour
#define hours
#define house
#define hover
#define how
#define howd
#define huge
#define huh
#define human
#define humans
#define humming
#define hundred
#define hundreds
#define hurry
#define hurt
#define hurts
#define i
#define id
#define idea
#define ideas
#define idiots
#define if
#define ignacio
#define iguana
#define ill
#define illegally
#define illegitimate
#define im
#define image
#define imagine
#define imagines
#define important
#define impose
#define impossible
#define improve
#define in
#define incapacitated
#define inclusion
#define incorporating
#define incredible
#define individuals
#define industries
#define industry
#define inflatable
#define information
#define initial
#define inner
#define insane
#define insect
#define inside
#define inspector
#define instead
#define instinct
#define intend
#define intended
#define intends
#define interest
#define interested
#define interesting
#define interview
#define into
#define intrigues
#define invented
#define is
#define ish
#define isnt
#define issues
#define it
#define italian
#define itll
#define its
#define ive
#define j
#define jammed
#define janet
#define jar
#define jars
#define jazz
#define jealousy
#define jeanette
#define jell
#define jerks
#define jewish
#define jfk
#define job
#define jobs
#define jock
#define jocks
#define john
#define joke
#define judge
#define jump
#define jury
#define jurys
#define just
#define kachoo
#define kasell
#define keep
#define ken
#define kenneth
#define kenny
#define kept
#define key
#define keychain
#define keychains
#define kick
#define kid
#define kidding
#define kill
#define killer
#define kills
#define kind
#define king
#define kingdom
#define kite
#define klauss
#define knee
#define knew
#define knock
#define knocking
#define knocks
#define know
#define known
#define knows
#define koo
#define korean
#define krelman
#define la
#define label
#define ladies
#define land
#define larry
#define larvi
#define laser
#define last
#define late
#define latest
#define laugh
#define launch
#define lauren
#define law
#define laws
#define lawsuits
#define lawyer
#define lawyers
#define laying
#define layton
#define leader
#define leans
#define learn
#define least
#define leave
#define leaving
#define left
#define legal
#define legally
#define legitimate
#define legs
#define less
#define let
#define lets
#define letter
#define level
#define life
#define lifesaver
#define lifetime
#define lightning
#define lights
#define like
#define liked
#define likes
#define limit
#define line
#define lines
#define lint
#define liotta
#define lip
#define listen
#define listening
#define little
#define live
#define lived
#define lives
#define living
#define loaded
#define long
#define longer
#define look
#define looking
#define looks
#define lord
#define lordy
#define lose
#define losing
#define lost
#define lot
#define lou
#define lovable
#define love
#define loving
#define luckily
#define lucky
#define lunch
#define lust
#define m
#define ma
#define maam
#define machine
#define machines
#define made
#define madison
#define magazine
#define magic
#define major
#define make
#define makes
#define making
#define mall
#define mama
#define mamas
#define mamma
#define man
#define manhattan
#define mans
#define many
#define marry
#define marshal
#define martin
#define mass
#define massive
#define match
#define matter
#define matters
#define mattresses
#define may
#define maybe
#define mayday
#define me
#define meadow
#define mean
#define means
#define meant
#define meat
#define meet
#define meeting
#define men
#define mercy
#define met
#define metal
#define mia
#define micrograms
#define might
#define mighty
#define miles
#define milk
#define million
#define millions
#define mind
#define minds
#define mine
#define minute
#define minutes
#define miss
#define missile
#define mission
#define mistake
#define mite
#define mixed
#define mom
#define moment
#define money
#define monkeys
#define monsters
#define montgomery
#define montgomerys
#define moose
#define mooseblood
#define moosebloods
#define more
#define mosquito
#define most
#define motels
#define moth
#define motion
#define mouth
#define move
#define moved
#define moves
#define movies
#define moving
#define mr
#define much
#define multinational
#define murphys
#define museum
#define mushroom
#define must
#define mustache
#define my
#define myself
#define mystery
#define n
#define nah
#define name
#define names
#define nation
#define natural
#define nature
#define nauseous
#define neck
#define nectar
#define need
#define needed
#define needing
#define needs
#define negative
#define negotiate
#define neither
#define nerves
#define never
#define new
#define newbies
#define news
#define next
#define nice
#define nicest
#define nickel
#define nicknames
#define nicotine
#define night
#define nightmare
#define nine
#define ninety
#define no
#define nobody
#define non
#define normal
#define nose
#define not_
#define nothing
#define now
#define nowhere
#define nows
#define npr
#define number
#define nurse
#define o
#define objection
#define obviously
#define occasion
#define of
#define off
#define office
#define officer
#define official
#define oh
#define ohung
#define ok
#define old
#define on
#define onboard
#define once
#define one
#define ones
#define only
#define onto
#define ooh
#define oolumbus
#define open
#define opened
#define opening
#define or_
#define order
#define ordinary
#define organic
#define orientation
#define other
#define our
#define ours
#define ourselves
#define out
#define outside
#define over
#define overcome
#define overworked
#define ow
#define own
#define pack
#define packaging
#define packing
#define pact
#define pages
#define paid
#define pain
#define panicking
#define panicky
#define pants
#define parade
#define parasite
#define parents
#define park
#define part
#define partly
#define pasadena
#define passed
#define passengers
#define patch
#define pathetic
#define pattern
#define paw
#define paying
#define pea
#define people
#define percent
#define perfect
#define perfectly
#define perhaps
#define person
#define perversion
#define petunias
#define photos
#define pic
#define pick
#define picking
#define picture
#define piece
#define pierce
#define pillows
#define pilot
#define pinch
#define pincushion
#define pinhead
#define pinheads
#define pinned
#define pitch
#define place
#define plane
#define planet
#define planned
#define plant
#define player
#define playing
#define please
#define point
#define pointed
#define pointless
#define pointy
#define poison
#define police
#define pollen
#define pollinate
#define pollination
#define pomp
#define pond
#define poo
#define poodle
#define pool
#define poor
#define position
#define positions
#define possession
#define possibly
#define pound
#define pour
#define poured
#define pourer
#define pouring
#define power
#define prance
#define predicted
#define prefer
#define presented
#define presiding
#define pretty
#define previous
#define princess
#define private
#define privilege
#define problem
#define proceed
#define produce
#define production
#define products
#define profit
#define profiting
#define proof
#define protect
#define proud
#define provide
#define psychotic
#define puddle
#define puff
#define puffs
#define pull
#define pulling
#define pulsating
#define pure
#define put
#define putting
#define quadrant
#define qualities
#define queen
#define queens
#define question
#define quiet
#define quite
#define quotes
#define race
#define radio
#define raft
#define rain
#define raised
#define ralph
#define ray
#define razor
#define ready
#define real
#define realized
#define really
#define reason
#define recall
#define regret
#define rehearsal
#define rehearse
#define relationship
#define relieved
#define remember
#define remind
#define reminder
#define remodeling
#define removal
#define remove
#define repollination
#define report
#define reporting
#define reports
#define representing
#define respond
#define rest
#define restricted
#define restroom
#define result
#define resume
#define returning
#define reverse
#define rhythm
#define ridiculous
#define riding
#define right
#define ring
#define rings
#define rise
#define roaches
#define road
#define robotics
#define roger
#define roller
#define rookie
#define rookies
#define room
#define root
#define roses
#define rotate
#define row
#define royal
#define royalty
#define ruined
#define rum
#define rumor
#define rumors
#define run
#define runs
#define runway
#define said
#define sale
#define same
#define san
#define sandwich
#define sat
#define savages
#define save
#define saved
#define saves
#define saw
#define say
#define saying
#define says
#define scale
#define scared
#define scariest
#define scary
#define scene
#define scent
#define school
#define schoolshospitals
#define science
#define scott
#define scramble
#define screaming
#define second
#define secret
#define security
#define see
#define seem
#define seems
#define seen
#define select
#define semi
#define sense
#define session
#define set
#define settlement
#define seven
#define seventy
#define shack
#define shake
#define sharp
#define shave
#define she
#define sheep
#define shenanigans
#define shes
#define shirt
#define shoes
#define shop
#define shorts
#define shot
#define should
#define shoulders
#define shouldnt
#define show
#define shut
#define shutdown
#define shutting
#define side
#define sides
#define sign
#define signal
#define silkworm
#define simple
#define sir
#define sit
#define situation
#define six
#define sixty
#define size
#define skill
#define skills
#define sky
#define slap
#define slapping
#define slat
#define slaves
#define sleeping
#define sleeves
#define slogan
#define slow
#define smack
#define small
#define smell
#define smells
#define smelly
#define smoke
#define smoker
#define smoking
#define snack
#define snap
#define so
#define society
#define sole
#define some
#define someone
#define something
#define sometimes
#define somewhere
#define son
#define sons
#define soothing
#define sorry
#define sort
#define sound
#define sounds
#define source
#define south
#define speak
#define special
#define species
#define specifically
#define spider
#define spiders
#define spin
#define spitting
#define sports
#define spot
#define spray
#define sprinkle
#define squinty
#define squirrel
#define stage
#define stairs
#define stall
#define stand
#define star
#define start
#define starting
#define statement
#define status
#define stay
#define stealing
#define stellar
#define stem
#define step
#define steps
#define steroids
#define stick
#define stickball
#define sticks
#define still
#define sting
#define stinger
#define stingers
#define stingin
#define stingings
#define stink
#define stinks
#define stir
#define stirrer
#define stirring
#define stolen
#define stop
#define stopping
#define stores
#define storm
#define story
#define strand
#define straw
#define stress
#define stripe
#define striped
#define stripes
#define stripey
#define strive
#define strong
#define students
#define studio
#define stuff
#define stung
#define stunt
#define such
#define suck
#define suckers
#define sucking
#define sue
#define sugar
#define sugars
#define suicide
#define sumner
#define sun
#define sunflower
#define superior
#define supervisor
#define supplier
#define support
#define supporting
#define suppose
#define supposed
#define sure
#define surface
#define surfs
#define surprise
#define surprised
#define surrounded
#define survive
#define suspenders
#define suspenseful
#define suspicion
#define sweater
#define sweet
#define sweeteners
#define sweetheart
#define sword
#define symbol
#define syrup
#define t
#define tacoma
#define tail
#define take
#define taken
#define takes
#define taking
#define tale
#define talk
#define talking
#define tap
#define tar
#define tarmac
#define tattoo
#define taught
#define tea
#define team
#define technically
#define technology
#define tell
#define temper
#define ten
#define tennis
#define tension
#define term
#define terrific
#define test
#define testing
#define than
#define thank
#define thanks
#define that
#define thats
#define the
#define their
#define them
#define thems
#define then
#define thenand
#define theory
#define there
#define theres
#define these
#define they
#define theyll
#define theyre
#define theyve
#define thing
#define things
#define think
#define thinking
#define third
#define thirty
#define this
#define thiss
#define thomas
#define thorax
#define those
#define though
#define thought
#define thousand
#define three
#define throat
#define through
#define throw
#define tie
#define tight
#define till
#define timberland
#define time
#define times
#define tin
#define tiny
#define tivo
#define to
#define today
#define todays
#define toe
#define toes
#define together
#define told
#define tolerate
#define tomorrow
#define tone
#define tonight
#define too
#define took
#define tooth
#define top
#define topsy
#define total
#define toupee
#define tournament
#define tower
#define trade
#define traffic
#define trained
#define tram
#define trap
#define travolta
#define treat
#define tri
#define trial
#define trickery
#define tried
#define trimmer
#define triple
#define trouble
#define truck
#define true
#define try
#define trying
#define tub
#define tulip
#define tuna
#define turmoil
#define turn
#define turns
#define turtle
#define turvy
#define tv
#define tweezers
#define twenty
#define twice
#define two
#define uh
#define unbelievable
#define uncle
#define unconscious
#define under
#define understand
#define understands
#define unfortunately
#define unholy
#define unless
#define unnecessary
#define up
#define upset
#define us
#define use
#define using
#define usually
#define v
#define vacations
#define valiant
#define valuable
#define value
#define van
#define vanderhayden
#define vanessa
#define vannie
#define vegetables
#define veins
#define venom
#define ventriloquism
#define versus
#define very
#define vibram
#define victory
#define virtually
#define visual
#define vogue
#define voice
#define wait
#define waits
#define walk
#define wall
#define walls
#define wanna
#define want
#define wanted
#define wants
#define warming
#define wars
#define was
#define washers
#define washington
#define wasnt
#define wasp
#define waste
#define watch
#define water
#define watermelon
#define wave
#define wax
#define way
#define we
#define weakness
#define wearing
#define weather
#define weave
#define wed
#define wedding
#define week
#define weekend
#define weird
#define welcome
#define well
#define were
#define weve
#define whassup
#define what
#define whatd
#define whatever
#define whats
#define whatsoever
#define when
#define where
#define wheres
#define wherever
#define which
#define white
#define who
#define whole
#define whos
#define whose
#define why
#define will
#define wilting
#define win
#define wind
#define window
#define winged
#define wings
#define winter
#define wipe
#define wiper
#define wish
#define with
#define without
#define witness
#define wizardry
#define woman
#define womens
#define won
#define wonder
#define wont
#define wooden
#define woods
#define work
#define worked
#define working
#define works
#define world
#define worry
#define worse
#define would
#define wouldnt
#define wow
#define wrangler
#define wrap
#define write
#define wrong
#define y
#define yall
#define yeah
#define year
#define yearning
#define years
#define yell
#define yelling
#define yellow
#define yes
#define yesterday
#define yet
#define yogi
#define yogurt
#define york
#define you
#define youll
#define your
#define youre
#define yourjob
#define yours
#define yourself
#define youve
#define yowser
#define zero
